name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: " 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 "
        issue-message: "Message that will be displayed on users' first issue"
        pr-message: "successfully merege and contribite the code"
